//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Data.EntityClient;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Linq;
using System.Runtime.Serialization;
using System.Xml.Serialization;

[assembly: EdmSchemaAttribute()]
#region EDM Relationship Metadata

[assembly: EdmRelationshipAttribute("hrModel", "FK__tbl_grad__grad_f__2B0A656D", "tbl_applicant_personal", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(HR.Model.tbl_applicant_personal), "tbl_grad", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(HR.Model.tbl_grad), true)]
[assembly: EdmRelationshipAttribute("hrModel", "FK__tbl_hsc__hsc_fk___2645B050", "tbl_applicant_personal", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(HR.Model.tbl_applicant_personal), "tbl_hsc", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(HR.Model.tbl_hsc), true)]
[assembly: EdmRelationshipAttribute("hrModel", "FK__tbl_mas__mas_fk___2FCF1A8A", "tbl_applicant_personal", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(HR.Model.tbl_applicant_personal), "tbl_mas", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(HR.Model.tbl_mas), true)]
[assembly: EdmRelationshipAttribute("hrModel", "FK__tbl_ssc__ssc_fk___2180FB33", "tbl_applicant_personal", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(HR.Model.tbl_applicant_personal), "tbl_ssc", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(HR.Model.tbl_ssc), true)]

#endregion

namespace HR.Model
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class hrEntities : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new hrEntities object using the connection string found in the 'hrEntities' section of the application configuration file.
        /// </summary>
        public hrEntities() : base("name=hrEntities", "hrEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new hrEntities object.
        /// </summary>
        public hrEntities(string connectionString) : base(connectionString, "hrEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new hrEntities object.
        /// </summary>
        public hrEntities(EntityConnection connection) : base(connection, "hrEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<tbl_applicant_personal> tbl_applicant_personal
        {
            get
            {
                if ((_tbl_applicant_personal == null))
                {
                    _tbl_applicant_personal = base.CreateObjectSet<tbl_applicant_personal>("tbl_applicant_personal");
                }
                return _tbl_applicant_personal;
            }
        }
        private ObjectSet<tbl_applicant_personal> _tbl_applicant_personal;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<tbl_department> tbl_department
        {
            get
            {
                if ((_tbl_department == null))
                {
                    _tbl_department = base.CreateObjectSet<tbl_department>("tbl_department");
                }
                return _tbl_department;
            }
        }
        private ObjectSet<tbl_department> _tbl_department;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<tbl_grad> tbl_grad
        {
            get
            {
                if ((_tbl_grad == null))
                {
                    _tbl_grad = base.CreateObjectSet<tbl_grad>("tbl_grad");
                }
                return _tbl_grad;
            }
        }
        private ObjectSet<tbl_grad> _tbl_grad;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<tbl_hsc> tbl_hsc
        {
            get
            {
                if ((_tbl_hsc == null))
                {
                    _tbl_hsc = base.CreateObjectSet<tbl_hsc>("tbl_hsc");
                }
                return _tbl_hsc;
            }
        }
        private ObjectSet<tbl_hsc> _tbl_hsc;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<tbl_mas> tbl_mas
        {
            get
            {
                if ((_tbl_mas == null))
                {
                    _tbl_mas = base.CreateObjectSet<tbl_mas>("tbl_mas");
                }
                return _tbl_mas;
            }
        }
        private ObjectSet<tbl_mas> _tbl_mas;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<tbl_ssc> tbl_ssc
        {
            get
            {
                if ((_tbl_ssc == null))
                {
                    _tbl_ssc = base.CreateObjectSet<tbl_ssc>("tbl_ssc");
                }
                return _tbl_ssc;
            }
        }
        private ObjectSet<tbl_ssc> _tbl_ssc;

        #endregion

        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the tbl_applicant_personal EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTotbl_applicant_personal(tbl_applicant_personal tbl_applicant_personal)
        {
            base.AddObject("tbl_applicant_personal", tbl_applicant_personal);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the tbl_department EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTotbl_department(tbl_department tbl_department)
        {
            base.AddObject("tbl_department", tbl_department);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the tbl_grad EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTotbl_grad(tbl_grad tbl_grad)
        {
            base.AddObject("tbl_grad", tbl_grad);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the tbl_hsc EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTotbl_hsc(tbl_hsc tbl_hsc)
        {
            base.AddObject("tbl_hsc", tbl_hsc);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the tbl_mas EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTotbl_mas(tbl_mas tbl_mas)
        {
            base.AddObject("tbl_mas", tbl_mas);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the tbl_ssc EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTotbl_ssc(tbl_ssc tbl_ssc)
        {
            base.AddObject("tbl_ssc", tbl_ssc);
        }

        #endregion

    }

    #endregion

    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="hrModel", Name="tbl_applicant_personal")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class tbl_applicant_personal : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new tbl_applicant_personal object.
        /// </summary>
        /// <param name="ap_id">Initial value of the ap_id property.</param>
        /// <param name="ap_name">Initial value of the ap_name property.</param>
        /// <param name="ap_password">Initial value of the ap_password property.</param>
        /// <param name="ap_cninc">Initial value of the ap_cninc property.</param>
        /// <param name="ap_phone1">Initial value of the ap_phone1 property.</param>
        /// <param name="ap_phone2">Initial value of the ap_phone2 property.</param>
        /// <param name="ap_email">Initial value of the ap_email property.</param>
        /// <param name="ap_image">Initial value of the ap_image property.</param>
        public static tbl_applicant_personal Createtbl_applicant_personal(global::System.Int32 ap_id, global::System.String ap_name, global::System.String ap_password, global::System.String ap_cninc, global::System.String ap_phone1, global::System.String ap_phone2, global::System.String ap_email, global::System.String ap_image)
        {
            tbl_applicant_personal tbl_applicant_personal = new tbl_applicant_personal();
            tbl_applicant_personal.ap_id = ap_id;
            tbl_applicant_personal.ap_name = ap_name;
            tbl_applicant_personal.ap_password = ap_password;
            tbl_applicant_personal.ap_cninc = ap_cninc;
            tbl_applicant_personal.ap_phone1 = ap_phone1;
            tbl_applicant_personal.ap_phone2 = ap_phone2;
            tbl_applicant_personal.ap_email = ap_email;
            tbl_applicant_personal.ap_image = ap_image;
            return tbl_applicant_personal;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 ap_id
        {
            get
            {
                return _ap_id;
            }
            set
            {
                if (_ap_id != value)
                {
                    Onap_idChanging(value);
                    ReportPropertyChanging("ap_id");
                    _ap_id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("ap_id");
                    Onap_idChanged();
                }
            }
        }
        private global::System.Int32 _ap_id;
        partial void Onap_idChanging(global::System.Int32 value);
        partial void Onap_idChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String ap_name
        {
            get
            {
                return _ap_name;
            }
            set
            {
                Onap_nameChanging(value);
                ReportPropertyChanging("ap_name");
                _ap_name = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("ap_name");
                Onap_nameChanged();
            }
        }
        private global::System.String _ap_name;
        partial void Onap_nameChanging(global::System.String value);
        partial void Onap_nameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String ap_password
        {
            get
            {
                return _ap_password;
            }
            set
            {
                Onap_passwordChanging(value);
                ReportPropertyChanging("ap_password");
                _ap_password = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("ap_password");
                Onap_passwordChanged();
            }
        }
        private global::System.String _ap_password;
        partial void Onap_passwordChanging(global::System.String value);
        partial void Onap_passwordChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String ap_cninc
        {
            get
            {
                return _ap_cninc;
            }
            set
            {
                Onap_cnincChanging(value);
                ReportPropertyChanging("ap_cninc");
                _ap_cninc = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("ap_cninc");
                Onap_cnincChanged();
            }
        }
        private global::System.String _ap_cninc;
        partial void Onap_cnincChanging(global::System.String value);
        partial void Onap_cnincChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String ap_phone1
        {
            get
            {
                return _ap_phone1;
            }
            set
            {
                Onap_phone1Changing(value);
                ReportPropertyChanging("ap_phone1");
                _ap_phone1 = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("ap_phone1");
                Onap_phone1Changed();
            }
        }
        private global::System.String _ap_phone1;
        partial void Onap_phone1Changing(global::System.String value);
        partial void Onap_phone1Changed();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String ap_phone2
        {
            get
            {
                return _ap_phone2;
            }
            set
            {
                Onap_phone2Changing(value);
                ReportPropertyChanging("ap_phone2");
                _ap_phone2 = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("ap_phone2");
                Onap_phone2Changed();
            }
        }
        private global::System.String _ap_phone2;
        partial void Onap_phone2Changing(global::System.String value);
        partial void Onap_phone2Changed();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String ap_email
        {
            get
            {
                return _ap_email;
            }
            set
            {
                Onap_emailChanging(value);
                ReportPropertyChanging("ap_email");
                _ap_email = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("ap_email");
                Onap_emailChanged();
            }
        }
        private global::System.String _ap_email;
        partial void Onap_emailChanging(global::System.String value);
        partial void Onap_emailChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String ap_image
        {
            get
            {
                return _ap_image;
            }
            set
            {
                Onap_imageChanging(value);
                ReportPropertyChanging("ap_image");
                _ap_image = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("ap_image");
                Onap_imageChanged();
            }
        }
        private global::System.String _ap_image;
        partial void Onap_imageChanging(global::System.String value);
        partial void Onap_imageChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> ap_gender
        {
            get
            {
                return _ap_gender;
            }
            set
            {
                Onap_genderChanging(value);
                ReportPropertyChanging("ap_gender");
                _ap_gender = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("ap_gender");
                Onap_genderChanged();
            }
        }
        private Nullable<global::System.Int32> _ap_gender;
        partial void Onap_genderChanging(Nullable<global::System.Int32> value);
        partial void Onap_genderChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> ap_dob
        {
            get
            {
                return _ap_dob;
            }
            set
            {
                Onap_dobChanging(value);
                ReportPropertyChanging("ap_dob");
                _ap_dob = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("ap_dob");
                Onap_dobChanged();
            }
        }
        private Nullable<global::System.DateTime> _ap_dob;
        partial void Onap_dobChanging(Nullable<global::System.DateTime> value);
        partial void Onap_dobChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("hrModel", "FK__tbl_grad__grad_f__2B0A656D", "tbl_grad")]
        public EntityCollection<tbl_grad> tbl_grad
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<tbl_grad>("hrModel.FK__tbl_grad__grad_f__2B0A656D", "tbl_grad");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<tbl_grad>("hrModel.FK__tbl_grad__grad_f__2B0A656D", "tbl_grad", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("hrModel", "FK__tbl_hsc__hsc_fk___2645B050", "tbl_hsc")]
        public EntityCollection<tbl_hsc> tbl_hsc
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<tbl_hsc>("hrModel.FK__tbl_hsc__hsc_fk___2645B050", "tbl_hsc");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<tbl_hsc>("hrModel.FK__tbl_hsc__hsc_fk___2645B050", "tbl_hsc", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("hrModel", "FK__tbl_mas__mas_fk___2FCF1A8A", "tbl_mas")]
        public EntityCollection<tbl_mas> tbl_mas
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<tbl_mas>("hrModel.FK__tbl_mas__mas_fk___2FCF1A8A", "tbl_mas");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<tbl_mas>("hrModel.FK__tbl_mas__mas_fk___2FCF1A8A", "tbl_mas", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("hrModel", "FK__tbl_ssc__ssc_fk___2180FB33", "tbl_ssc")]
        public EntityCollection<tbl_ssc> tbl_ssc
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<tbl_ssc>("hrModel.FK__tbl_ssc__ssc_fk___2180FB33", "tbl_ssc");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<tbl_ssc>("hrModel.FK__tbl_ssc__ssc_fk___2180FB33", "tbl_ssc", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="hrModel", Name="tbl_department")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class tbl_department : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new tbl_department object.
        /// </summary>
        /// <param name="dept_id">Initial value of the dept_id property.</param>
        /// <param name="dept_name">Initial value of the dept_name property.</param>
        public static tbl_department Createtbl_department(global::System.Int32 dept_id, global::System.String dept_name)
        {
            tbl_department tbl_department = new tbl_department();
            tbl_department.dept_id = dept_id;
            tbl_department.dept_name = dept_name;
            return tbl_department;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 dept_id
        {
            get
            {
                return _dept_id;
            }
            set
            {
                if (_dept_id != value)
                {
                    Ondept_idChanging(value);
                    ReportPropertyChanging("dept_id");
                    _dept_id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("dept_id");
                    Ondept_idChanged();
                }
            }
        }
        private global::System.Int32 _dept_id;
        partial void Ondept_idChanging(global::System.Int32 value);
        partial void Ondept_idChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String dept_name
        {
            get
            {
                return _dept_name;
            }
            set
            {
                Ondept_nameChanging(value);
                ReportPropertyChanging("dept_name");
                _dept_name = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("dept_name");
                Ondept_nameChanged();
            }
        }
        private global::System.String _dept_name;
        partial void Ondept_nameChanging(global::System.String value);
        partial void Ondept_nameChanged();

        #endregion

    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="hrModel", Name="tbl_grad")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class tbl_grad : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new tbl_grad object.
        /// </summary>
        /// <param name="grad_id">Initial value of the grad_id property.</param>
        /// <param name="grad_institute">Initial value of the grad_institute property.</param>
        public static tbl_grad Createtbl_grad(global::System.Int32 grad_id, global::System.String grad_institute)
        {
            tbl_grad tbl_grad = new tbl_grad();
            tbl_grad.grad_id = grad_id;
            tbl_grad.grad_institute = grad_institute;
            return tbl_grad;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 grad_id
        {
            get
            {
                return _grad_id;
            }
            set
            {
                if (_grad_id != value)
                {
                    Ongrad_idChanging(value);
                    ReportPropertyChanging("grad_id");
                    _grad_id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("grad_id");
                    Ongrad_idChanged();
                }
            }
        }
        private global::System.Int32 _grad_id;
        partial void Ongrad_idChanging(global::System.Int32 value);
        partial void Ongrad_idChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Double> grad_percentage
        {
            get
            {
                return _grad_percentage;
            }
            set
            {
                Ongrad_percentageChanging(value);
                ReportPropertyChanging("grad_percentage");
                _grad_percentage = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("grad_percentage");
                Ongrad_percentageChanged();
            }
        }
        private Nullable<global::System.Double> _grad_percentage;
        partial void Ongrad_percentageChanging(Nullable<global::System.Double> value);
        partial void Ongrad_percentageChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String grad_institute
        {
            get
            {
                return _grad_institute;
            }
            set
            {
                Ongrad_instituteChanging(value);
                ReportPropertyChanging("grad_institute");
                _grad_institute = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("grad_institute");
                Ongrad_instituteChanged();
            }
        }
        private global::System.String _grad_institute;
        partial void Ongrad_instituteChanging(global::System.String value);
        partial void Ongrad_instituteChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String grad_doc
        {
            get
            {
                return _grad_doc;
            }
            set
            {
                Ongrad_docChanging(value);
                ReportPropertyChanging("grad_doc");
                _grad_doc = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("grad_doc");
                Ongrad_docChanged();
            }
        }
        private global::System.String _grad_doc;
        partial void Ongrad_docChanging(global::System.String value);
        partial void Ongrad_docChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> grad_fk_ap_id
        {
            get
            {
                return _grad_fk_ap_id;
            }
            set
            {
                Ongrad_fk_ap_idChanging(value);
                ReportPropertyChanging("grad_fk_ap_id");
                _grad_fk_ap_id = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("grad_fk_ap_id");
                Ongrad_fk_ap_idChanged();
            }
        }
        private Nullable<global::System.Int32> _grad_fk_ap_id;
        partial void Ongrad_fk_ap_idChanging(Nullable<global::System.Int32> value);
        partial void Ongrad_fk_ap_idChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("hrModel", "FK__tbl_grad__grad_f__2B0A656D", "tbl_applicant_personal")]
        public tbl_applicant_personal tbl_applicant_personal
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<tbl_applicant_personal>("hrModel.FK__tbl_grad__grad_f__2B0A656D", "tbl_applicant_personal").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<tbl_applicant_personal>("hrModel.FK__tbl_grad__grad_f__2B0A656D", "tbl_applicant_personal").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<tbl_applicant_personal> tbl_applicant_personalReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<tbl_applicant_personal>("hrModel.FK__tbl_grad__grad_f__2B0A656D", "tbl_applicant_personal");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<tbl_applicant_personal>("hrModel.FK__tbl_grad__grad_f__2B0A656D", "tbl_applicant_personal", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="hrModel", Name="tbl_hsc")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class tbl_hsc : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new tbl_hsc object.
        /// </summary>
        /// <param name="hsc_id">Initial value of the hsc_id property.</param>
        /// <param name="hsc_institute">Initial value of the hsc_institute property.</param>
        public static tbl_hsc Createtbl_hsc(global::System.Int32 hsc_id, global::System.String hsc_institute)
        {
            tbl_hsc tbl_hsc = new tbl_hsc();
            tbl_hsc.hsc_id = hsc_id;
            tbl_hsc.hsc_institute = hsc_institute;
            return tbl_hsc;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 hsc_id
        {
            get
            {
                return _hsc_id;
            }
            set
            {
                if (_hsc_id != value)
                {
                    Onhsc_idChanging(value);
                    ReportPropertyChanging("hsc_id");
                    _hsc_id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("hsc_id");
                    Onhsc_idChanged();
                }
            }
        }
        private global::System.Int32 _hsc_id;
        partial void Onhsc_idChanging(global::System.Int32 value);
        partial void Onhsc_idChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Double> hsc_percentage
        {
            get
            {
                return _hsc_percentage;
            }
            set
            {
                Onhsc_percentageChanging(value);
                ReportPropertyChanging("hsc_percentage");
                _hsc_percentage = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("hsc_percentage");
                Onhsc_percentageChanged();
            }
        }
        private Nullable<global::System.Double> _hsc_percentage;
        partial void Onhsc_percentageChanging(Nullable<global::System.Double> value);
        partial void Onhsc_percentageChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String hsc_institute
        {
            get
            {
                return _hsc_institute;
            }
            set
            {
                Onhsc_instituteChanging(value);
                ReportPropertyChanging("hsc_institute");
                _hsc_institute = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("hsc_institute");
                Onhsc_instituteChanged();
            }
        }
        private global::System.String _hsc_institute;
        partial void Onhsc_instituteChanging(global::System.String value);
        partial void Onhsc_instituteChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String hsc_doc
        {
            get
            {
                return _hsc_doc;
            }
            set
            {
                Onhsc_docChanging(value);
                ReportPropertyChanging("hsc_doc");
                _hsc_doc = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("hsc_doc");
                Onhsc_docChanged();
            }
        }
        private global::System.String _hsc_doc;
        partial void Onhsc_docChanging(global::System.String value);
        partial void Onhsc_docChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> hsc_fk_ap_id
        {
            get
            {
                return _hsc_fk_ap_id;
            }
            set
            {
                Onhsc_fk_ap_idChanging(value);
                ReportPropertyChanging("hsc_fk_ap_id");
                _hsc_fk_ap_id = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("hsc_fk_ap_id");
                Onhsc_fk_ap_idChanged();
            }
        }
        private Nullable<global::System.Int32> _hsc_fk_ap_id;
        partial void Onhsc_fk_ap_idChanging(Nullable<global::System.Int32> value);
        partial void Onhsc_fk_ap_idChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("hrModel", "FK__tbl_hsc__hsc_fk___2645B050", "tbl_applicant_personal")]
        public tbl_applicant_personal tbl_applicant_personal
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<tbl_applicant_personal>("hrModel.FK__tbl_hsc__hsc_fk___2645B050", "tbl_applicant_personal").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<tbl_applicant_personal>("hrModel.FK__tbl_hsc__hsc_fk___2645B050", "tbl_applicant_personal").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<tbl_applicant_personal> tbl_applicant_personalReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<tbl_applicant_personal>("hrModel.FK__tbl_hsc__hsc_fk___2645B050", "tbl_applicant_personal");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<tbl_applicant_personal>("hrModel.FK__tbl_hsc__hsc_fk___2645B050", "tbl_applicant_personal", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="hrModel", Name="tbl_mas")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class tbl_mas : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new tbl_mas object.
        /// </summary>
        /// <param name="mas_id">Initial value of the mas_id property.</param>
        /// <param name="mas_institute">Initial value of the mas_institute property.</param>
        public static tbl_mas Createtbl_mas(global::System.Int32 mas_id, global::System.String mas_institute)
        {
            tbl_mas tbl_mas = new tbl_mas();
            tbl_mas.mas_id = mas_id;
            tbl_mas.mas_institute = mas_institute;
            return tbl_mas;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 mas_id
        {
            get
            {
                return _mas_id;
            }
            set
            {
                if (_mas_id != value)
                {
                    Onmas_idChanging(value);
                    ReportPropertyChanging("mas_id");
                    _mas_id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("mas_id");
                    Onmas_idChanged();
                }
            }
        }
        private global::System.Int32 _mas_id;
        partial void Onmas_idChanging(global::System.Int32 value);
        partial void Onmas_idChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Double> mas_percentage
        {
            get
            {
                return _mas_percentage;
            }
            set
            {
                Onmas_percentageChanging(value);
                ReportPropertyChanging("mas_percentage");
                _mas_percentage = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("mas_percentage");
                Onmas_percentageChanged();
            }
        }
        private Nullable<global::System.Double> _mas_percentage;
        partial void Onmas_percentageChanging(Nullable<global::System.Double> value);
        partial void Onmas_percentageChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String mas_institute
        {
            get
            {
                return _mas_institute;
            }
            set
            {
                Onmas_instituteChanging(value);
                ReportPropertyChanging("mas_institute");
                _mas_institute = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("mas_institute");
                Onmas_instituteChanged();
            }
        }
        private global::System.String _mas_institute;
        partial void Onmas_instituteChanging(global::System.String value);
        partial void Onmas_instituteChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String mas_doc
        {
            get
            {
                return _mas_doc;
            }
            set
            {
                Onmas_docChanging(value);
                ReportPropertyChanging("mas_doc");
                _mas_doc = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("mas_doc");
                Onmas_docChanged();
            }
        }
        private global::System.String _mas_doc;
        partial void Onmas_docChanging(global::System.String value);
        partial void Onmas_docChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> mas_fk_ap_id
        {
            get
            {
                return _mas_fk_ap_id;
            }
            set
            {
                Onmas_fk_ap_idChanging(value);
                ReportPropertyChanging("mas_fk_ap_id");
                _mas_fk_ap_id = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("mas_fk_ap_id");
                Onmas_fk_ap_idChanged();
            }
        }
        private Nullable<global::System.Int32> _mas_fk_ap_id;
        partial void Onmas_fk_ap_idChanging(Nullable<global::System.Int32> value);
        partial void Onmas_fk_ap_idChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("hrModel", "FK__tbl_mas__mas_fk___2FCF1A8A", "tbl_applicant_personal")]
        public tbl_applicant_personal tbl_applicant_personal
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<tbl_applicant_personal>("hrModel.FK__tbl_mas__mas_fk___2FCF1A8A", "tbl_applicant_personal").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<tbl_applicant_personal>("hrModel.FK__tbl_mas__mas_fk___2FCF1A8A", "tbl_applicant_personal").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<tbl_applicant_personal> tbl_applicant_personalReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<tbl_applicant_personal>("hrModel.FK__tbl_mas__mas_fk___2FCF1A8A", "tbl_applicant_personal");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<tbl_applicant_personal>("hrModel.FK__tbl_mas__mas_fk___2FCF1A8A", "tbl_applicant_personal", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="hrModel", Name="tbl_ssc")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class tbl_ssc : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new tbl_ssc object.
        /// </summary>
        /// <param name="ssc_id">Initial value of the ssc_id property.</param>
        /// <param name="ssc_institute">Initial value of the ssc_institute property.</param>
        public static tbl_ssc Createtbl_ssc(global::System.Int32 ssc_id, global::System.String ssc_institute)
        {
            tbl_ssc tbl_ssc = new tbl_ssc();
            tbl_ssc.ssc_id = ssc_id;
            tbl_ssc.ssc_institute = ssc_institute;
            return tbl_ssc;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 ssc_id
        {
            get
            {
                return _ssc_id;
            }
            set
            {
                if (_ssc_id != value)
                {
                    Onssc_idChanging(value);
                    ReportPropertyChanging("ssc_id");
                    _ssc_id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("ssc_id");
                    Onssc_idChanged();
                }
            }
        }
        private global::System.Int32 _ssc_id;
        partial void Onssc_idChanging(global::System.Int32 value);
        partial void Onssc_idChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Double> ssc_percentage
        {
            get
            {
                return _ssc_percentage;
            }
            set
            {
                Onssc_percentageChanging(value);
                ReportPropertyChanging("ssc_percentage");
                _ssc_percentage = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("ssc_percentage");
                Onssc_percentageChanged();
            }
        }
        private Nullable<global::System.Double> _ssc_percentage;
        partial void Onssc_percentageChanging(Nullable<global::System.Double> value);
        partial void Onssc_percentageChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String ssc_institute
        {
            get
            {
                return _ssc_institute;
            }
            set
            {
                Onssc_instituteChanging(value);
                ReportPropertyChanging("ssc_institute");
                _ssc_institute = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("ssc_institute");
                Onssc_instituteChanged();
            }
        }
        private global::System.String _ssc_institute;
        partial void Onssc_instituteChanging(global::System.String value);
        partial void Onssc_instituteChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String ssc_doc
        {
            get
            {
                return _ssc_doc;
            }
            set
            {
                Onssc_docChanging(value);
                ReportPropertyChanging("ssc_doc");
                _ssc_doc = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("ssc_doc");
                Onssc_docChanged();
            }
        }
        private global::System.String _ssc_doc;
        partial void Onssc_docChanging(global::System.String value);
        partial void Onssc_docChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> ssc_fk_ap_id
        {
            get
            {
                return _ssc_fk_ap_id;
            }
            set
            {
                Onssc_fk_ap_idChanging(value);
                ReportPropertyChanging("ssc_fk_ap_id");
                _ssc_fk_ap_id = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("ssc_fk_ap_id");
                Onssc_fk_ap_idChanged();
            }
        }
        private Nullable<global::System.Int32> _ssc_fk_ap_id;
        partial void Onssc_fk_ap_idChanging(Nullable<global::System.Int32> value);
        partial void Onssc_fk_ap_idChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("hrModel", "FK__tbl_ssc__ssc_fk___2180FB33", "tbl_applicant_personal")]
        public tbl_applicant_personal tbl_applicant_personal
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<tbl_applicant_personal>("hrModel.FK__tbl_ssc__ssc_fk___2180FB33", "tbl_applicant_personal").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<tbl_applicant_personal>("hrModel.FK__tbl_ssc__ssc_fk___2180FB33", "tbl_applicant_personal").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<tbl_applicant_personal> tbl_applicant_personalReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<tbl_applicant_personal>("hrModel.FK__tbl_ssc__ssc_fk___2180FB33", "tbl_applicant_personal");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<tbl_applicant_personal>("hrModel.FK__tbl_ssc__ssc_fk___2180FB33", "tbl_applicant_personal", value);
                }
            }
        }

        #endregion

    }

    #endregion

    
}
